apiVersion: v1
kind: Secret
metadata:
  name: securityscan-secrets
  namespace: securityscan
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://app:password@cluster.mongodb.net/securityscan?retryWrites=true&w=majority"
  REDIS_URL: "redis://:redispassword@redis-master.securityscan.svc.cluster.local:6379"
  JWT_SECRET: "replace-with-cryptographically-secure-random-256-bit-key"
  S3_ACCESS_KEY: "AKIAEXAMPLEACCESSKEY"
  S3_SECRET_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
