// === Authorization ===

export enum AuthorizationState {
  PENDING = 'PENDING',
  AUTHORIZED = 'AUTHORIZED',
  EXPIRED = 'EXPIRED',
  REVOKED = 'REVOKED',
}

// === Scan ===

export enum ScanStatus {
  CREATED = 'CREATED',
  VALIDATING = 'VALIDATING',
  QUEUED = 'QUEUED',
  DISCOVERING = 'DISCOVERING',
  CRAWLING = 'CRAWLING',
  PASSIVE_ANALYSIS = 'PASSIVE_ANALYSIS',
  ACTIVE_TESTING = 'ACTIVE_TESTING',
  API_TESTING = 'API_TESTING',
  VERIFYING = 'VERIFYING',
  EVIDENCE_COLLECTION = 'EVIDENCE_COLLECTION',
  REPORTING = 'REPORTING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  TIMEOUT = 'TIMEOUT',
}

export enum ScanProfile {
  PASSIVE = 'PASSIVE',
  QUICK = 'QUICK',
  WEB_STANDARD = 'WEB_STANDARD',
  API_STANDARD = 'API_STANDARD',
  AUTHENTICATED = 'AUTHENTICATED',
  AUTHORIZATION = 'AUTHORIZATION',
  FULL_ASSESSMENT = 'FULL_ASSESSMENT',
  CICD = 'CICD',
  PRODUCTION_SAFE = 'PRODUCTION_SAFE',
  SECURITY_LAB = 'SECURITY_LAB',
  // Backward-compatible aliases
  LIGHT = 'QUICK',
  STANDARD = 'WEB_STANDARD',
  AGGRESSIVE = 'FULL_ASSESSMENT',
}

// === Severity & Confidence ===

export enum Severity {
  CRITICAL = 'CRITICAL',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
  INFO = 'INFO',
}

export enum Confidence {
  CONFIRMED = 'CONFIRMED',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
}

// === Findings ===

export enum FindingStatus {
  CANDIDATE = 'CANDIDATE',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  ACCEPTED = 'ACCEPTED',
  MITIGATED = 'MITIGATED',
  REOPENED = 'REOPENED',
}

// === Detection ===

export enum DetectionCategory {
  ACCESS_CONTROL = 'ACCESS_CONTROL',
  AUTHENTICATION = 'AUTHENTICATION',
  AUTHORIZATION = 'AUTHORIZATION',
  INJECTION = 'INJECTION',
  XSS = 'XSS',
  CSRF = 'CSRF',
  SSRF = 'SSRF',
  PATH_TRAVERSAL = 'PATH_TRAVERSAL',
  FILE_UPLOAD = 'FILE_UPLOAD',
  MISCONFIGURATION = 'MISCONFIGURATION',
  CRYPTOGRAPHY = 'CRYPTOGRAPHY',
  INFORMATION_DISCLOSURE = 'INFORMATION_DISCLOSURE',
  API_SECURITY = 'API_SECURITY',
  BUSINESS_LOGIC = 'BUSINESS_LOGIC',
  SESSION_MANAGEMENT = 'SESSION_MANAGEMENT',
}

export enum DetectionType {
  PASSIVE = 'PASSIVE',
  ACTIVE = 'ACTIVE',
}

// === Authentication ===

export enum AuthType {
  NONE = 'NONE',
  COOKIE_SESSION = 'COOKIE_SESSION',
  BEARER_TOKEN = 'BEARER_TOKEN',
  JWT = 'JWT',
  API_KEY = 'API_KEY',
  OAUTH2 = 'OAUTH2',
  OIDC = 'OIDC',
  CUSTOM_HEADER = 'CUSTOM_HEADER',
  MTLS = 'MTLS',
}

export enum AuthProfileRole {
  ANONYMOUS = 'ANONYMOUS',
  USER = 'USER',
  MANAGER = 'MANAGER',
  ADMIN = 'ADMIN',
  CUSTOM = 'CUSTOM',
}

// === API ===

export enum ApiType {
  REST = 'REST',
  GRAPHQL = 'GRAPHQL',
  WEBSOCKET = 'WEBSOCKET',
  GRPC = 'GRPC',
  SOAP = 'SOAP',
}

export enum ApiSchemaFormat {
  OPENAPI_JSON = 'OPENAPI_JSON',
  OPENAPI_YAML = 'OPENAPI_YAML',
  SWAGGER_JSON = 'SWAGGER_JSON',
  SWAGGER_YAML = 'SWAGGER_YAML',
  GRAPHQL_SDL = 'GRAPHQL_SDL',
  GRAPHQL_INTROSPECTION = 'GRAPHQL_INTROSPECTION',
  WSDL = 'WSDL',
  GRPC_PROTO = 'GRPC_PROTO',
}

// === HTTP ===

export enum HttpMethod {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  PATCH = 'PATCH',
  DELETE = 'DELETE',
  HEAD = 'HEAD',
  OPTIONS = 'OPTIONS',
  TRACE = 'TRACE',
}

// === Environment ===

export enum TargetEnvironment {
  DEVELOPMENT = 'DEVELOPMENT',
  STAGING = 'STAGING',
  PRODUCTION = 'PRODUCTION',
  TESTING = 'TESTING',
}

// === Report ===

export enum ReportFormat {
  HTML = 'HTML',
  PDF = 'PDF',
  JSON = 'JSON',
  SARIF = 'SARIF',
}

// === Scope Validation ===

export enum ScopeValidationResult {
  ALLOWED = 'ALLOWED',
  BLOCKED_HOST = 'BLOCKED_HOST',
  BLOCKED_PATH = 'BLOCKED_PATH',
  BLOCKED_PRIVATE_IP = 'BLOCKED_PRIVATE_IP',
  BLOCKED_EXCLUDED = 'BLOCKED_EXCLUDED',
  RATE_LIMITED = 'RATE_LIMITED',
  REQUEST_LIMIT_EXCEEDED = 'REQUEST_LIMIT_EXCEEDED',
  DURATION_EXCEEDED = 'DURATION_EXCEEDED',
  SCAN_CANCELLED = 'SCAN_CANCELLED',
}

// === Audit ===

export enum AuditAction {
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  PROJECT_CREATED = 'PROJECT_CREATED',
  PROJECT_UPDATED = 'PROJECT_UPDATED',
  PROJECT_DELETED = 'PROJECT_DELETED',
  TARGET_CREATED = 'TARGET_CREATED',
  TARGET_UPDATED = 'TARGET_UPDATED',
  TARGET_AUTHORIZED = 'TARGET_AUTHORIZED',
  TARGET_REVOKED = 'TARGET_REVOKED',
  SCAN_CREATED = 'SCAN_CREATED',
  SCAN_STARTED = 'SCAN_STARTED',
  SCAN_CANCELLED = 'SCAN_CANCELLED',
  SCAN_COMPLETED = 'SCAN_COMPLETED',
  SCAN_FAILED = 'SCAN_FAILED',
  REPORT_GENERATED = 'REPORT_GENERATED',
  CONFIG_CHANGED = 'CONFIG_CHANGED',
}
