import type { ISecurityRule } from '@securityscan/contracts';
import { DetectionCategory, DetectionType, Severity, Confidence } from '@securityscan/contracts';

export class SecurityRuleRegistry {
  private rules: Map<string, ISecurityRule> = new Map();

  register(rule: ISecurityRule): void {
    this.rules.set(rule.id, rule);
  }

  get(id: string): ISecurityRule | undefined {
    return this.rules.get(id);
  }

  getAll(): ISecurityRule[] {
    return Array.from(this.rules.values());
  }

  getByCategory(category: DetectionCategory): ISecurityRule[] {
    return this.getAll().filter((r) => r.category === category);
  }

  getByType(type: DetectionType): ISecurityRule[] {
    return this.getAll().filter((r) => r.type === type);
  }
}

export const PASSIVE_RULES: ISecurityRule[] = [
  {
    id: 'SEC-HDR-001',
    name: 'Missing Strict-Transport-Security Header',
    description: 'The response does not include a Strict-Transport-Security header.',
    category: DetectionCategory.MISCONFIGURATION,
    type: DetectionType.PASSIVE,
    severity: Severity.MEDIUM,
    confidence: Confidence.CONFIRMED,
    cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:L/I:N/A:N',
    cvssScore: 3.1,
    owasp: ['A05:2021'],
    apiOwasp: ['API8:2023'],
    cwe: ['CWE-319'],
    wstg: ['WSTG-CONF-07'],
    asvs: ['V14.4.3'],
    portswigger: [],
    remediation: 'Add Strict-Transport-Security header with appropriate max-age.',
    references: ['https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security'],
    enabled: true,
    tags: ['headers', 'tls'],
  },
  {
    id: 'SEC-HDR-002',
    name: 'Missing X-Content-Type-Options Header',
    description: 'The response does not include X-Content-Type-Options: nosniff.',
    category: DetectionCategory.MISCONFIGURATION,
    type: DetectionType.PASSIVE,
    severity: Severity.LOW,
    confidence: Confidence.CONFIRMED,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:N',
    cvssScore: 4.3,
    owasp: ['A05:2021'],
    apiOwasp: ['API8:2023'],
    cwe: ['CWE-693'],
    wstg: ['WSTG-CONF-07'],
    asvs: ['V14.4.2'],
    portswigger: [],
    remediation: 'Add X-Content-Type-Options: nosniff header.',
    references: ['https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options'],
    enabled: true,
    tags: ['headers'],
  },
  {
    id: 'SEC-HDR-003',
    name: 'Missing X-Frame-Options Header',
    description: 'The response does not include X-Frame-Options header.',
    category: DetectionCategory.MISCONFIGURATION,
    type: DetectionType.PASSIVE,
    severity: Severity.MEDIUM,
    confidence: Confidence.CONFIRMED,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:N',
    cvssScore: 4.3,
    owasp: ['A05:2021'],
    apiOwasp: [],
    cwe: ['CWE-1021'],
    wstg: ['WSTG-CONF-07'],
    asvs: ['V14.4.1'],
    portswigger: ['https://portswigger.net/web-security/clickjacking'],
    remediation: 'Add X-Frame-Options: DENY or SAMEORIGIN header.',
    references: ['https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options'],
    enabled: true,
    tags: ['headers', 'clickjacking'],
  },
  {
    id: 'SEC-HDR-004',
    name: 'Missing Content-Security-Policy Header',
    description: 'The response does not include a Content-Security-Policy header.',
    category: DetectionCategory.MISCONFIGURATION,
    type: DetectionType.PASSIVE,
    severity: Severity.MEDIUM,
    confidence: Confidence.CONFIRMED,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N',
    cvssScore: 5.4,
    owasp: ['A05:2021'],
    apiOwasp: [],
    cwe: ['CWE-693'],
    wstg: ['WSTG-CONF-07'],
    asvs: ['V14.4.1'],
    portswigger: [],
    remediation: 'Implement a Content-Security-Policy header with appropriate directives.',
    references: ['https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP'],
    enabled: true,
    tags: ['headers', 'csp', 'xss'],
  },
  {
    id: 'SEC-HDR-005',
    name: 'Server Version Disclosure',
    description: 'The Server header discloses version information.',
    category: DetectionCategory.INFORMATION_DISCLOSURE,
    type: DetectionType.PASSIVE,
    severity: Severity.INFO,
    confidence: Confidence.CONFIRMED,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N',
    cvssScore: 5.3,
    owasp: ['A05:2021'],
    apiOwasp: ['API8:2023'],
    cwe: ['CWE-200'],
    wstg: ['WSTG-INFO-02'],
    asvs: ['V14.3.3'],
    portswigger: [],
    remediation: 'Remove or minimize version information in the Server header.',
    references: [],
    enabled: true,
    tags: ['headers', 'info-disclosure'],
  },
  {
    id: 'SEC-HDR-006',
    name: 'X-Powered-By Header Present',
    description: 'The X-Powered-By header discloses technology stack information.',
    category: DetectionCategory.INFORMATION_DISCLOSURE,
    type: DetectionType.PASSIVE,
    severity: Severity.INFO,
    confidence: Confidence.CONFIRMED,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N',
    cvssScore: 5.3,
    owasp: ['A05:2021'],
    apiOwasp: ['API8:2023'],
    cwe: ['CWE-200'],
    wstg: ['WSTG-INFO-02'],
    asvs: ['V14.3.3'],
    portswigger: [],
    remediation: 'Remove the X-Powered-By header.',
    references: [],
    enabled: true,
    tags: ['headers', 'info-disclosure'],
  },
  {
    id: 'SEC-CORS-001',
    name: 'Permissive CORS Policy',
    description: 'The Access-Control-Allow-Origin header is set to wildcard (*).',
    category: DetectionCategory.MISCONFIGURATION,
    type: DetectionType.PASSIVE,
    severity: Severity.MEDIUM,
    confidence: Confidence.CONFIRMED,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N',
    cvssScore: 5.4,
    owasp: ['A05:2021'],
    apiOwasp: ['API8:2023'],
    cwe: ['CWE-942'],
    wstg: ['WSTG-CONF-07'],
    asvs: ['V14.4.6'],
    portswigger: ['https://portswigger.net/web-security/cors'],
    remediation: 'Restrict CORS to specific trusted origins.',
    references: ['https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS'],
    enabled: true,
    tags: ['cors', 'headers'],
  },
  {
    id: 'SEC-COOKIE-001',
    name: 'Cookie Without HttpOnly Flag',
    description: 'A Set-Cookie header does not include the HttpOnly flag.',
    category: DetectionCategory.SESSION_MANAGEMENT,
    type: DetectionType.PASSIVE,
    severity: Severity.MEDIUM,
    confidence: Confidence.CONFIRMED,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:N/A:N',
    cvssScore: 4.3,
    owasp: ['A05:2021'],
    apiOwasp: [],
    cwe: ['CWE-1004'],
    wstg: ['WSTG-SESS-02'],
    asvs: ['V3.4.2'],
    portswigger: [],
    remediation: 'Add the HttpOnly flag to sensitive cookies.',
    references: [],
    enabled: true,
    tags: ['cookies', 'session'],
  },
  {
    id: 'SEC-COOKIE-002',
    name: 'Cookie Without Secure Flag',
    description: 'A Set-Cookie header does not include the Secure flag.',
    category: DetectionCategory.SESSION_MANAGEMENT,
    type: DetectionType.PASSIVE,
    severity: Severity.MEDIUM,
    confidence: Confidence.CONFIRMED,
    cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:L/I:N/A:N',
    cvssScore: 3.1,
    owasp: ['A05:2021'],
    apiOwasp: [],
    cwe: ['CWE-614'],
    wstg: ['WSTG-SESS-02'],
    asvs: ['V3.4.1'],
    portswigger: [],
    remediation: 'Add the Secure flag to cookies.',
    references: [],
    enabled: true,
    tags: ['cookies', 'session'],
  },
  {
    id: 'SEC-COOKIE-003',
    name: 'Cookie Without SameSite Attribute',
    description: 'A Set-Cookie header does not include the SameSite attribute.',
    category: DetectionCategory.SESSION_MANAGEMENT,
    type: DetectionType.PASSIVE,
    severity: Severity.LOW,
    confidence: Confidence.CONFIRMED,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:N',
    cvssScore: 4.3,
    owasp: ['A05:2021'],
    apiOwasp: [],
    cwe: ['CWE-1275'],
    wstg: ['WSTG-SESS-02'],
    asvs: ['V3.4.3'],
    portswigger: [],
    remediation: 'Add SameSite=Strict or SameSite=Lax attribute to cookies.',
    references: [],
    enabled: true,
    tags: ['cookies', 'csrf'],
  },
];

export const ACTIVE_RULES: ISecurityRule[] = [
  {
    id: 'SEC-XSS-001',
    name: 'Reflected Cross-Site Scripting (XSS)',
    description: 'User input is reflected in the response without proper encoding.',
    category: DetectionCategory.XSS,
    type: DetectionType.ACTIVE,
    severity: Severity.HIGH,
    confidence: Confidence.MEDIUM,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N',
    cvssScore: 6.1,
    owasp: ['A03:2021'],
    apiOwasp: [],
    cwe: ['CWE-79'],
    wstg: ['WSTG-INPV-01'],
    asvs: ['V5.3.1', 'V5.3.3'],
    portswigger: ['https://portswigger.net/web-security/cross-site-scripting/reflected'],
    remediation: 'Implement proper output encoding and Content-Security-Policy.',
    references: ['https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html'],
    enabled: true,
    tags: ['xss', 'injection'],
  },
  {
    id: 'SEC-SQLI-001',
    name: 'SQL Injection',
    description: 'The application appears vulnerable to SQL injection attacks.',
    category: DetectionCategory.INJECTION,
    type: DetectionType.ACTIVE,
    severity: Severity.CRITICAL,
    confidence: Confidence.MEDIUM,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    cvssScore: 9.8,
    owasp: ['A03:2021'],
    apiOwasp: ['API8:2023'],
    cwe: ['CWE-89'],
    wstg: ['WSTG-INPV-05'],
    asvs: ['V5.3.4', 'V5.3.5'],
    portswigger: ['https://portswigger.net/web-security/sql-injection'],
    remediation: 'Use parameterized queries or prepared statements.',
    references: ['https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html'],
    enabled: true,
    tags: ['sqli', 'injection'],
  },
  {
    id: 'SEC-PT-001',
    name: 'Path Traversal',
    description: 'The application may be vulnerable to path traversal attacks.',
    category: DetectionCategory.PATH_TRAVERSAL,
    type: DetectionType.ACTIVE,
    severity: Severity.HIGH,
    confidence: Confidence.MEDIUM,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N',
    cvssScore: 7.5,
    owasp: ['A01:2021'],
    apiOwasp: [],
    cwe: ['CWE-22'],
    wstg: ['WSTG-ATHZ-01'],
    asvs: ['V12.3.1'],
    portswigger: ['https://portswigger.net/web-security/file-path-traversal'],
    remediation: 'Validate and sanitize file paths. Use allowlists for file access.',
    references: [],
    enabled: true,
    tags: ['path-traversal'],
  },
  {
    id: 'SEC-BOLA-001',
    name: 'Broken Object Level Authorization (BOLA/IDOR)',
    description: 'The application does not properly verify object-level authorization.',
    category: DetectionCategory.AUTHORIZATION,
    type: DetectionType.ACTIVE,
    severity: Severity.HIGH,
    confidence: Confidence.MEDIUM,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N',
    cvssScore: 8.1,
    owasp: ['A01:2021'],
    apiOwasp: ['API1:2023'],
    cwe: ['CWE-639'],
    wstg: ['WSTG-ATHZ-04'],
    asvs: ['V4.1.1', 'V4.1.2'],
    portswigger: ['https://portswigger.net/web-security/access-control/idor'],
    remediation: 'Implement proper object-level authorization checks.',
    references: [],
    enabled: true,
    tags: ['bola', 'idor', 'authorization'],
  },
];
