export interface AsvsRequirement {
  id: string; // e.g. 'V14.4.1'
  section: string;
  chapter: string;
  description: string;
  level: 1 | 2 | 3;
  cwes: string[];
}

export const ASVS_V403: Record<string, AsvsRequirement> = {
  'V2.2.1': {
    id: 'V2.2.1',
    section: 'V2',
    chapter: 'Authentication',
    description: 'Verify that anti-automation controls are effective at mitigating credential stuffing and brute-force attacks.',
    level: 1,
    cwes: ['CWE-307'],
  },
  'V3.4.1': {
    id: 'V3.4.1',
    section: 'V3',
    chapter: 'Session Management',
    description: 'Verify that cookie-based session tokens have the Secure attribute set.',
    level: 1,
    cwes: ['CWE-614'],
  },
  'V3.4.2': {
    id: 'V3.4.2',
    section: 'V3',
    chapter: 'Session Management',
    description: 'Verify that cookie-based session tokens have the HttpOnly attribute set.',
    level: 1,
    cwes: ['CWE-1004'],
  },
  'V3.4.3': {
    id: 'V3.4.3',
    section: 'V3',
    chapter: 'Session Management',
    description: 'Verify that cookie-based session tokens have the SameSite attribute configured to Lax or Strict.',
    level: 1,
    cwes: ['CWE-1275'],
  },
  'V4.1.1': {
    id: 'V4.1.1',
    section: 'V4',
    chapter: 'Access Control',
    description: 'Verify that the application enforces access control rules on a trusted service layer, especially for object-level access.',
    level: 1,
    cwes: ['CWE-639', 'CWE-285'],
  },
  'V4.1.2': {
    id: 'V4.1.2',
    section: 'V4',
    chapter: 'Access Control',
    description: 'Verify that user and data attributes and policy information used by access control decisions cannot be manipulated by the end user.',
    level: 1,
    cwes: ['CWE-639'],
  },
  'V4.1.3': {
    id: 'V4.1.3',
    section: 'V4',
    chapter: 'Access Control',
    description: 'Verify that the principle of least privilege exists - users should only be able to access authorized functions.',
    level: 1,
    cwes: ['CWE-285'],
  },
  'V4.2.1': {
    id: 'V4.2.1',
    section: 'V4',
    chapter: 'Access Control',
    description: 'Verify that sensitive operations utilize anti-CSRF tokens or SameSite attributes to prevent Cross-Site Request Forgery.',
    level: 1,
    cwes: ['CWE-352'],
  },
  'V5.3.1': {
    id: 'V5.3.1',
    section: 'V5',
    chapter: 'Validation, Sanitization and Encoding',
    description: 'Verify that output encoding is relevant for the interpreter and context required, preventing Cross-Site Scripting (XSS).',
    level: 1,
    cwes: ['CWE-79'],
  },
  'V5.3.4': {
    id: 'V5.3.4',
    section: 'V5',
    chapter: 'Validation, Sanitization and Encoding',
    description: 'Verify that data selection or database queries use parameterized queries, ORMs, or stored procedures.',
    level: 1,
    cwes: ['CWE-89'],
  },
  'V12.3.1': {
    id: 'V12.3.1',
    section: 'V12',
    chapter: 'File and Resources',
    description: 'Verify that user-supplied input is not used directly with filesystem APIs to prevent path traversal.',
    level: 1,
    cwes: ['CWE-22'],
  },
  'V12.6.1': {
    id: 'V12.6.1',
    section: 'V12',
    chapter: 'File and Resources',
    description: 'Verify that the web server or application validates remote URLs against an allowlist before fetching resources (SSRF).',
    level: 1,
    cwes: ['CWE-918'],
  },
  'V13.1.4': {
    id: 'V13.1.4',
    section: 'V13',
    chapter: 'API and Web Service',
    description: 'Verify that GraphQL schemas enforce query depth limits and query complexity analysis to prevent DoS.',
    level: 2,
    cwes: ['CWE-400'],
  },
  'V14.3.1': {
    id: 'V14.3.1',
    section: 'V14',
    chapter: 'Configuration',
    description: 'Verify that debug interfaces and unnecessary features such as GraphQL schema introspection are disabled in production.',
    level: 1,
    cwes: ['CWE-200'],
  },
  'V14.3.3': {
    id: 'V14.3.3',
    section: 'V14',
    chapter: 'Configuration',
    description: 'Verify that the web or application server does not expose version numbers via Server or X-Powered-By response headers.',
    level: 1,
    cwes: ['CWE-200'],
  },
  'V14.4.1': {
    id: 'V14.4.1',
    section: 'V14',
    chapter: 'Configuration',
    description: 'Verify that every HTTP response includes a Content-Security-Policy (CSP) header.',
    level: 1,
    cwes: ['CWE-693'],
  },
  'V14.4.2': {
    id: 'V14.4.2',
    section: 'V14',
    chapter: 'Configuration',
    description: 'Verify that every HTTP response includes an X-Content-Type-Options: nosniff header.',
    level: 1,
    cwes: ['CWE-693'],
  },
  'V14.4.3': {
    id: 'V14.4.3',
    section: 'V14',
    chapter: 'Configuration',
    description: 'Verify that every HTTP response includes an X-Frame-Options or CSP frame-ancestors header to prevent clickjacking.',
    level: 1,
    cwes: ['CWE-1021'],
  },
  'V14.4.4': {
    id: 'V14.4.4',
    section: 'V14',
    chapter: 'Configuration',
    description: 'Verify that all responses sent over HTTPS include a Strict-Transport-Security (HSTS) header.',
    level: 1,
    cwes: ['CWE-319'],
  },
  'V14.4.6': {
    id: 'V14.4.6',
    section: 'V14',
    chapter: 'Configuration',
    description: 'Verify that Cross-Origin Resource Sharing (CORS) Access-Control-Allow-Origin header is not set to wildcard (*) with credentials.',
    level: 1,
    cwes: ['CWE-942'],
  },
};
