import { ScanModel, TargetModel, FindingModel, ReportModel } from '@securityscan/database';
import { ReportFormat, ScanStatus } from '@securityscan/contracts';
import { ReportGenerator } from '@securityscan/reporting';
import { createLogger } from '@securityscan/shared';

const logger = createLogger('worker-reporting');

export async function runReportingWorker(scanId: string): Promise<string> {
  const scan = await ScanModel.findById(scanId);
  if (!scan) throw new Error('Scan not found');

  const target = await TargetModel.findById(scan.targetId);
  if (!target) throw new Error('Target not found');

  const allFindings = await FindingModel.find({ scanId: scan._id });
  const reportGen = new ReportGenerator();
  const summary = reportGen.generateSummary(allFindings.map((f) => f.toObject() as any));

  const title = `Security Scan Report - ${target.name}`;
  const scope = {
    targetUrl: target.baseUrl,
    allowedHosts: target.scope.allowedHosts,
    excludedHosts: target.scope.excludedHosts,
    scanProfile: scan.profile,
    startedAt: scan.startedAt,
    completedAt: new Date(),
  };

  const content = reportGen.generateJSON({
    title,
    scope,
    findings: allFindings.map((f) => f.toObject() as any),
    generatedAt: new Date(),
  });

  const report = await ReportModel.create({
    scanId: scan._id,
    projectId: scan.projectId,
    targetId: scan.targetId,
    format: ReportFormat.JSON,
    title,
    generatedAt: new Date(),
    scope,
    summary,
    content,
  });

  await ScanModel.findByIdAndUpdate(scanId, {
    status: ScanStatus.COMPLETED,
    completedAt: new Date(),
    'progress.phase': ScanStatus.COMPLETED,
  });

  logger.info({ scanId, reportId: report._id }, 'Report generated by reporting worker');
  return report._id.toString();
}
